[package]
name = "login_system"
version = "0.1.0"
edition = "2021"

[lib]
name = "login_system"
path = "src/lib.rs"

[[bin]]
name = "login_system_bin"
path = "src/main.rs"

[dependencies]
hello-macro = { path = "hello_macro" }
hello-macro-derive = { path = "hello_macro/hello_macro_derive" }
